name: Build, Push, and Deploy Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
      
      
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_KEY: ${{ secrets.EC2_KEY }}
        
    steps:   
    - name: Build and upload Docker images
      run: |
        services=("room-service" "services" "users-service")
        
        for service in "${services[@]}"
        do
          if [ -d "$service" ]; then
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest ./$service
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:latest
          else
            echo "Could not find directory for service $service"
            exit 1
          fi
        done

    - name: Fix routes in docker-compose.yml
      run: |
        sed -i 's|build: \./|build: ../|g' ./docker/docker-compose.yml
        echo "Updated content from docker-compose.yml:"
        cat ./docker/docker-compose.yml

    - name: Execute Docker Compose
      run: |
        docker-compose -f ./docker/docker-compose.yml up -d
        - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}  
          script: |
            docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
            docker pull ${{ secrets.DOCKER_USERNAME }}/room-service:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/services:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/users-service:latest
            docker stop room-service || true
            docker stop services || true
            docker stop users-service || true
            docker rm room-service || true
            docker rm services || true
            docker rm users-service || true
            docker run -d --name room-service -p 8080:3004 ${{ secrets.DOCKER_USERNAME }}/room-service:latest
            docker run -d --name services -p 8081:3006 ${{ secrets.DOCKER_USERNAME }}/services:latest
            docker run -d --name users-service -p 8082:3005 ${{ secrets.DOCKER_USERNAME }}/users-service:latest